# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CCACHE=/opt/homebrew/bin/ccache
SC=/usr/bin/xcrun -sdk macosx swiftc
RC=/opt/homebrew/bin/rustc
CU=/usr/bin/clang
MM=/usr/bin/xcrun -sdk macosx clang
MXX=/usr/bin/xcrun -sdk macosx clang
CC=/usr/bin/xcrun -sdk macosx clang
GC=/opt/homebrew/bin/go
AS=/usr/bin/xcrun -sdk macosx clang
CXX=/usr/bin/xcrun -sdk macosx clang
FC=/opt/homebrew/bin/gfortran

AR=/usr/bin/xcrun -sdk macosx ar
RCAR=/opt/homebrew/bin/rustc
GCAR=/opt/homebrew/bin/go
SCSH=/usr/bin/xcrun -sdk macosx swiftc
RCSH=/opt/homebrew/bin/rustc
SH=/usr/bin/xcrun -sdk macosx clang++
FCSH=/opt/homebrew/bin/gfortran
SCLD=/usr/bin/xcrun -sdk macosx swiftc
RCLD=/opt/homebrew/bin/rustc
LD=/usr/bin/xcrun -sdk macosx clang++
FCLD=/opt/homebrew/bin/gfortran
GCLD=/opt/homebrew/bin/go

bbg-cli_GCFLAGS=
bbg-cli_GCLDFLAGS=

default:  bbg-cli

all:  bbg-cli

.PHONY: default all  bbg-cli

bbg-cli: bin/bbg-cli
bin/bbg-cli: build/.objs/bbg-cli/macosx/arm64/release/main.go.o build/.objs/bbg-cli/macosx/arm64/release/cmd/help.go.o build/.objs/bbg-cli/macosx/arm64/release/cmd/init.go.o
	@echo linking.release bbg-cli
	@mkdir -p bin
	@$(bbg-cli_GCLDFLAGS)$(GCLD) tool link -o bin/bbg-cli build/.objs/bbg-cli/macosx/arm64/release/main.go.o build/.objs/bbg-cli/macosx/arm64/release/cmd/help.go.o build/.objs/bbg-cli/macosx/arm64/release/cmd/init.go.o > build/.build.log 2>&1

build/.objs/bbg-cli/macosx/arm64/release/main.go.o: main.go
	@echo ccache compiling.release main.go
	@mkdir -p build/.objs/bbg-cli/macosx/arm64/release
	@$(GC) tool compile $(bbg-cli_GCFLAGS) -o build/.objs/bbg-cli/macosx/arm64/release/main.go.o main.go > build/.build.log 2>&1

build/.objs/bbg-cli/macosx/arm64/release/cmd/help.go.o: cmd/help.go
	@echo ccache compiling.release cmd/help.go
	@mkdir -p build/.objs/bbg-cli/macosx/arm64/release/cmd
	@$(GC) tool compile $(bbg-cli_GCFLAGS) -o build/.objs/bbg-cli/macosx/arm64/release/cmd/help.go.o cmd/help.go > build/.build.log 2>&1

build/.objs/bbg-cli/macosx/arm64/release/cmd/init.go.o: cmd/init.go
	@echo ccache compiling.release cmd/init.go
	@mkdir -p build/.objs/bbg-cli/macosx/arm64/release/cmd
	@$(GC) tool compile $(bbg-cli_GCFLAGS) -o build/.objs/bbg-cli/macosx/arm64/release/cmd/init.go.o cmd/init.go > build/.build.log 2>&1

clean:  clean_bbg-cli

clean_bbg-cli: 
	@rm -rf bin/bbg-cli
	@rm -rf bin/bbg-cli.dSYM
	@rm -rf build/.objs/bbg-cli/macosx/arm64/release/main.go.o
	@rm -rf build/.objs/bbg-cli/macosx/arm64/release/cmd/help.go.o
	@rm -rf build/.objs/bbg-cli/macosx/arm64/release/cmd/init.go.o

